import { Picture } from './picture';

export const PICTURES: Picture[] = [
  {id: 1, image: 'https://placehold.it/600x450/?text=First Slide', alt: 'First Slide', title: 'Title One'},
  {id: 2, image: 'https://placehold.it/600x450/?text=Second Slide', alt: 'Second Slide', title: 'Title Two'},
  {id: 3, image: 'https://placehold.it/600x450/?text=Third Slide', alt: 'Third Slide', title: 'Title Three'},
  {id: 4, image: 'https://placehold.it/600x450/?text=Fourth Slide', alt: 'Fourth Slide', title: 'Title Four'},
];

export const INTROPICTURES: Picture[] = [
  {id: 1, image: 'intro1.jpg', alt: 'Portland', title: 'Goodbye Portland'},
  {id: 2, image: 'intro2.jpg', alt: 'Above the Clouds', title: 'Cloudy Portland'},
  {id: 3, image: 'intro3.jpg', alt: 'Mt. St. Helens and Mt. Rainier', title: 'Mt. St. Helens and Mt. Rainier above the Clouds'},
  {id: 4, image: 'intro4.jpg', alt: 'Mt. Adams', title: 'Mt. Adams dominating the view'},
  {id: 5, image: 'intro5.jpg', alt: 'Columbia River', title: 'Look at all them circles'},
  {id: 6, image: 'intro6.jpg', alt: 'Columbia River', title: 'Even more circles'},
  {id: 7, image: 'intro7.jpg', alt: 'Columbia River', title: 'Circles with a dam'},
  {id: 8, image: 'intro8.jpg', alt: 'Bozeman', title: 'Flying over Bozeman'},
  {id: 9, image: 'intro9.jpg', alt: 'Bozeman', title: 'Goodbye Bozeman'},
  {id: 10, image: 'intro10.jpg', alt: 'Montana', title: 'Crazy Clouds'},
  {id: 11, image: 'intro11.jpg', alt: 'Montana', title: 'Is that a Horse?'},
  {id: 12, image: 'intro12.jpg', alt: 'Montana', title: 'More Crazy clouds'},
  {id: 13, image: 'intro13.jpg', alt: 'Illinois', title: 'Approaching Chicagoland'},
  {id: 14, image: 'intro14.jpg', alt: 'Illinois', title: 'Plentiful of Clouds near Chicagoland'},
  {id: 15, image: 'intro15.jpg', alt: 'Illinois', title: 'More crazy clouds near Chicagoland'},
  {id: 16, image: 'intro16.jpg', alt: 'Indiana', title: 'Passing by Lake Michigan in Indiana'},
  {id: 17, image: 'intro17.jpg', alt: 'Jenn and Adam', title: 'Long plane rides make you Crazy'},
  {id: 18, image: 'intro18.jpg', alt: 'Ohio & West Virginia', title: 'The Ohio River cutting through Ohio and West Virginia'},
  {id: 19, image: 'intro19.jpg', alt: 'Uniontown', title: 'Uniontown, Pennsylvania'},
  {id: 20, image: 'intro20.jpg', alt: 'Jenn & Adam', title: 'We\'re ready for this plane to land'},  
  {id: 21, image: 'laurel1.jpg', alt: 'Laurel', title: 'View from the Hotel'},
  {id: 22, image: 'laurel2.jpg', alt: 'Sunset', title: 'Sunset in Laurel'},
  {id: 23, image: 'laurel3.jpg', alt: 'Sunset', title: 'Sunset in Laurel'},
  {id: 24, image: 'laurel4.jpg', alt: 'Jenn and Neal', title: 'Two Deaths and a Chiropractic Treatment'},
  {id: 25, image: 'laurel5.jpg', alt: 'Jenn and Neal', title: 'Coming to a Hotel Room Near You'},
  {id: 26, image: 'laurel6.jpg', alt: 'Jenn and Neal', title: 'This is not part of the cirriculum'},
  {id: 27, image: 'laurel7.jpg', alt: 'Holiday Inn Express', title: 'Holiday Inn Express'}                    
];

export const BALTIMOREPICTURES: Picture[] = [
    {id: 1, image: 'baltimore1.jpg', alt: 'MT&T Bank Stadium', title: 'MT&T Bank Stadium', description: 'Home of the Baltimore Ravens'},
    {id: 2, image: 'baltimore2.jpg', alt: 'MT&T Bank Stadium', title: 'MT&T Bank Stadium', description: 'I finally got a picture of the football stadium'},
    {id: 3, image: 'baltimore3.jpg', alt: 'Baltimore', title: 'Welcome Back Baltimore', description: 'At least there\'s no Snow'},
    {id: 4, image: 'baltimore4.jpg', alt: 'Baltimore', title: 'Shake Shack'},
    {id: 5, image: 'baltimore5.jpg', alt: 'Baltimore World Trade Center', title: 'Baltimore World Trade Center', description: '9/11 Memorial'},
    {id: 6, image: 'baltimore6.jpg', alt: 'Baltimore Skyline', title: 'Baltimore Skyline'},
    {id: 7, image: 'baltimore7.jpg', alt: 'Chesapeake Ship', title: 'Chesapeake Ship'},
    {id: 8, image: 'baltimore8.jpg', alt: 'Chesapeake Ship', title: 'Chesapeake Ship'},
    {id: 9, image: 'baltimore9.jpg', alt: 'Inner Harbor', title: 'The Other Side of the Inner Harbor'},
    {id: 10, image: 'baltimore10.jpg', alt: 'National Aquarium', title: 'National Aquarium'},
    {id: 11, image: 'baltimore11.jpg', alt: 'National Aquarium', title: 'National Aquarium'},
    {id: 12, image: 'baltimore12.jpg', alt: 'Baltimore World Trade Center', title: 'Baltimore World Trade Center'},
    {id: 13, image: 'baltimore13.jpg', alt: 'Baltimore World Trade Center', title: 'Baltimore World Trade Center'},
    {id: 14, image: 'baltimore14.jpg', alt: 'Baltimore Skyline', title: 'Baltimore Skyline'},
    {id: 15, image: 'baltimore15.jpg', alt: 'Baltimore World Trade Center', title: 'Baltimore World Trade Center'},
    {id: 16, image: 'baltimore16.jpg', alt: 'Baltimore World Trade Center', title: 'Baltimore World Trade Center'},
    {id: 17, image: 'baltimore17.jpg', alt: 'National Aquarium from across the Harbor', title: 'National Aquarium from across the Harbor'},
    {id: 18, image: 'baltimore18.jpg', alt: 'U.S.S. Constellation', title: 'U.S.S. Constellation'},
    {id: 19, image: 'baltimore19.jpg', alt: 'U.S.S. Constellation', title: 'Anchor at U.S.S. Constellation'},
    {id: 20, image: 'baltimore20.jpg', alt: 'View from the Inner Harbor', title: 'View from the Inner Harbor'},
    {id: 21, image: 'baltimore21.jpg', alt: 'View from the Inner Harbor', title: 'View from the Inner Harbor'},
    {id: 22, image: 'baltimore22.jpg', alt: 'U.S.S. Constellation Museum', title: 'U.S.S. Constellation Museum'},
    {id: 23, image: 'baltimore23.jpg', alt: 'Baltimore Skyline', title: 'Baltimore Skyline', description: 'The Transamerica Tower, located on the far left, is the tallest building in Baltimore (and Maryland) at 529 feet'},
    {id: 24, image: 'baltimore24.jpg', alt: 'View from the Inner Harbor', title: 'View from the Inner Harbor', description: 'I love this view!'},
    {id: 25, image: 'baltimore25.jpg', alt: 'Jenn', title: 'Stand Proud, Jenn'},
    {id: 26, image: 'baltimore26.jpg', alt: 'Jenn', title: 'Another great picture of Jenn'},
    {id: 27, image: 'baltimore27.jpg', alt: 'Jenn', title: 'I Pledge the Alligence, to the Flag'},
    {id: 28, image: 'baltimore28.jpg', alt: 'Adam and Jenn', title: 'Adam taking a selfie of Jenn pledging the alligence'},
    {id: 29, image: 'baltimore29.jpg', alt: 'View from the Inner Harbor', title: 'View from the Inner Harbor'},
    {id: 30, image: 'baltimore30.jpg', alt: 'Baltimore World Trade Center', title: 'Baltimore World Trade Center'},
    {id: 31, image: 'baltimore31.jpg', alt: 'Jenn', title: 'Jenn at a different angle', description: 'Nice picture Neal'},
    {id: 32, image: 'baltimore32.jpg', alt: 'Adam', title: 'Captain Adam\'s Happy'},
    {id: 33, image: 'baltimore33.jpg', alt: 'Adam', title: 'On Top of the World'},
    {id: 34, image: 'baltimore34.jpg', alt: 'Adam and Jenn', title: 'Adam and Jenn'},
    {id: 35, image: 'baltimore35.jpg', alt: 'Adam and Jenn', title: 'Same Picture, different View'},
    {id: 36, image: 'baltimore36.jpg', alt: 'U.S.S. Constellation', title: 'U.S.S. Constellation'},
    {id: 37, image: 'baltimore37.jpg', alt: 'Jenn and Neal', title: 'Smile Neal'},
    {id: 38, image: 'baltimore38.jpg', alt: 'Jenn and Neal', title: 'Please Smile Neal'},
    {id: 39, image: 'baltimore39.jpg', alt: 'Jenn and Neal', title: 'That\'s not a Smile Neal'},
    {id: 40, image: 'baltimore40.jpg', alt: 'Jenn and Neal', title: 'Side View, still no Smile Neal'},
    {id: 41, image: 'baltimore41.jpg', alt: 'Jenn and Neal', title: 'Adam taking a picture of Neal taking a selfie of him and Jenn'},
    {id: 42, image: 'baltimore42.jpg', alt: 'Jenn and Neal', title: 'Almost there, Neal'},
    {id: 43, image: 'baltimore43.jpg', alt: 'Jenn and Neal', title: 'That\'s more like it, Neal'},
    {id: 44, image: 'baltimore44.jpg', alt: 'Jenn and Neal', title: 'Time for a Piggyback Ride'},
    {id: 45, image: 'baltimore45.jpg', alt: 'Baltimore Skyline', title: 'Baltimore Skyline', description: 'The second to the left prominent building, 100 East Pratt Street is the fifth tallest in the state.'},
    {id: 46, image: 'baltimore46.jpg', alt: 'U.S.S. Constellation', title: 'U.S.S. Constellation'},
    {id: 47, image: 'baltimore47.jpg', alt: 'U.S.S. Constellation', title: 'U.S.S. Constellation'},
    {id: 48, image: 'baltimore48.jpg', alt: 'U.S.S. Constellation', title: 'U.S.S. Constellation'},
    {id: 49, image: 'baltimore49.jpg', alt: 'Ripley\'s Believe it Or Not Odditorium', title: 'Ripley\'s Believe it Or Not Odditorium'},
    {id: 50, image: 'baltimore50.jpg', alt: 'U.S.S. Constellation', title: 'U.S.S. Constellation'},
    {id: 51, image: 'baltimore51.jpg', alt: 'View from the Inner Harbor', title: 'View from the Inner Harbor'},
    {id: 52, image: 'baltimore52.jpg', alt: 'Hebrew', title: 'Hebrew on the Streets', description: 'Jenn found this, good eye!'},
    {id: 53, image: 'baltimore53.jpg', alt: 'Baltimore World Trade Center', title: 'Baltimore World Trade Center'},
    {id: 54, image: 'baltimore54.jpg', alt: 'Baltimore Skyline', title: 'Baltimore Skyline', description: 'The second tallest building in Maryland, the Bank of America Building, is on the right with the bright yellow top'},
    {id: 55, image: 'baltimore55.jpg', alt: 'Baltimore Skyline', title: 'Baltimore Skyline'},
    {id: 56, image: 'baltimore56.jpg', alt: 'Baltimore Skyline', title: 'Baltimore Skyline'},
    {id: 57, image: 'baltimore57.jpg', alt: 'Baltimore Skyline', title: 'Baltimore Skyline'},
    {id: 58, image: 'baltimore58.jpg', alt: 'Baltimore Skyline', title: 'Baltimore SKyline'}                               
]

export const PIERPICTURES: Picture[] = [
    {id: 1, image: 'pier1.jpg', alt: 'Hard Rock Cafe', title: 'Hard Rock Cafe'},
    {id: 2, image: 'pier2.jpg', alt: 'Harbor', title: 'Harbor from the Pier'},
    {id: 3, image: 'pier3.jpg', alt: 'Phillips', title: 'Phillips Seafood'},
    {id: 4, image: 'pier4.jpg', alt: 'Jenn', title: 'Smile Jenn'},
    {id: 5, image: 'pier5.jpg', alt: 'Jenn', title: 'Not a Promotion of Barnes & Noble'},
    {id: 6, image: 'pier6.jpg', alt: 'Jenn', title: 'Jenn laughing'},
    {id: 7, image: 'pier7.jpg', alt: 'Pier 4', title: 'Pier 4'},
    {id: 8, image: 'pier8.jpg', alt: 'Adam', title: 'Selfie Time!'},
    {id: 9, image: 'pier9.jpg', alt: 'Dick\'s Last Resort', title: 'Dick\'s Last Resort'},
    {id: 10, image: 'pier10.jpg', alt: 'Grumpy', title: 'We\'re both Grumpy!'},
    {id: 11, image: 'pier11.jpg', alt: 'Pier 4', title: 'Pier 4'},
    {id: 12, image: 'pier12.jpg', alt: 'Fish', title: 'Fish'},  
    {id: 13, image: 'pier13.jpg', alt: 'Adam', title: 'Smile Adam!'},
    {id: 14, image: 'pier14.jpg', alt: 'View from the Pier', title: 'View from the Pier'},
    {id: 15, image: 'pier15.jpg', alt: 'View from the Pier', title: 'View from the Pier'}                
]

export const KEVINPICTURES: Picture[] = [
  {id: 1, image: 'kevin1.jpg', alt: 'Pho Kevin', title: 'Pho Kevin'},
  {id: 2, image: 'kevin2.jpg', alt: 'Thai Iced Tea', title: 'Thai Iced Tea'},
  {id: 3, image: 'kevin3.jpg', alt: 'Pho', title: 'Pho'}  
]

export const DINERPICTURES: Picture[] = [
  {id: 1, image: 'silver-diner1.jpg', alt: 'Silver Diner', title: 'Silver Diner'},
  {id: 2, image: 'silver-diner2.jpg', alt: 'Jenn', title: 'Smile Jenn'},
  {id: 3, image: 'silver-diner3.jpg', alt: 'Jenn', title: 'Is that Yummy Jenn?'},
  {id: 4, image: 'silver-diner4.jpg', alt: 'Wasabi Salmon Sliders', title: 'Wasabi Salmon Sliders'},  
]
/*    {id: , image: '.jpg', alt: '', title: ''},*/