import { Picture } from './picture';

export const PICTURES: Picture[] = [
  {id: 1, image: 'https://placehold.it/600x450/?text=First Slide', alt: 'First Slide', title: 'Title One', description: 'Random description One'},
  {id: 2, image: 'https://placehold.it/600x450/?text=Second Slide', alt: 'Second Slide', title: 'Title Two', description: 'Random description Two'},
  {id: 3, image: 'https://placehold.it/600x450/?text=Third Slide', alt: 'Third Slide', title: 'Title Three', description: 'Random description Three'},
  {id: 4, image: 'https://placehold.it/600x450/?text=Fourth Slide', alt: 'Fourth Slide', title: 'Title Four', description: 'Random description Four'},
];

export const INTROPICTURES: Picture[] = [
  {id: 1, image: 'https://s3-us-west-2.amazonaws.com/nadm2.bodiewebdesign.com/photos/intro1.jpg', alt: 'Portland', title: 'Goodbye Portland', description: 'Random description One'},
  {id: 2, image: 'https://s3-us-west-2.amazonaws.com/nadm2.bodiewebdesign.com/photos/intro2.jpg', alt: 'Above the Clouds', title: 'Cloudy Portland', description: 'Random description Two'},
  {id: 3, image: 'https://s3-us-west-2.amazonaws.com/nadm2.bodiewebdesign.com/photos/intro3.jpg', alt: 'Mt. St. Helens and Mt. Rainier', title: 'Mt. St. Helens and Mt. Rainier above the Clouds', description: 'Random description Three'},
  {id: 4, image: 'https://s3-us-west-2.amazonaws.com/nadm2.bodiewebdesign.com/photos/intro4.jpg', alt: 'Mt. Adams', title: 'Mt. Adams dominating the view', description: 'Random description Four'},
  {id: 5, image: 'https://s3-us-west-2.amazonaws.com/nadm2.bodiewebdesign.com/photos/intro5.jpg', alt: 'Columbia River', title: 'Look at all them circles', description: 'Random description One'},
  {id: 6, image: 'https://s3-us-west-2.amazonaws.com/nadm2.bodiewebdesign.com/photos/intro6.jpg', alt: 'Columbia River', title: 'Even more circles', description: 'Random description Two'},
  {id: 7, image: 'https://s3-us-west-2.amazonaws.com/nadm2.bodiewebdesign.com/photos/intro7.jpg', alt: 'Columbia River', title: 'Circles with a dam', description: 'Random description Three'},
  {id: 8, image: 'https://s3-us-west-2.amazonaws.com/nadm2.bodiewebdesign.com/photos/intro8.jpg', alt: 'Bozeman', title: 'Flying over Bozeman', description: 'Random description Four'},
  {id: 9, image: 'https://s3-us-west-2.amazonaws.com/nadm2.bodiewebdesign.com/photos/intro9.jpg', alt: 'Bozeman', title: 'Goodbye Bozeman', description: 'Random description One'},
  {id: 10, image: 'https://s3-us-west-2.amazonaws.com/nadm2.bodiewebdesign.com/photos/intro10.jpg', alt: 'Montana', title: 'Crazy Clouds', description: 'Random description Two'},
  {id: 11, image: 'https://s3-us-west-2.amazonaws.com/nadm2.bodiewebdesign.com/photos/intro11.jpg', alt: 'Montana', title: 'Is that a Horse?', description: 'Random description Three'},
  {id: 12, image: 'https://s3-us-west-2.amazonaws.com/nadm2.bodiewebdesign.com/photos/intro12.jpg', alt: 'Montana', title: 'More Crazy clouds', description: 'Random description Four'},
  {id: 13, image: 'https://s3-us-west-2.amazonaws.com/nadm2.bodiewebdesign.com/photos/intro13.jpg', alt: 'Illinois', title: 'Approaching Chicagoland', description: 'Random description One'},
  {id: 14, image: 'https://s3-us-west-2.amazonaws.com/nadm2.bodiewebdesign.com/photos/intro14.jpg', alt: 'Illinois', title: 'Plentiful of Clouds near Chicagoland', description: 'Random description Two'},
  {id: 15, image: 'https://s3-us-west-2.amazonaws.com/nadm2.bodiewebdesign.com/photos/intro15.jpg', alt: 'Illinois', title: 'More crazy clouds near Chicagoland', description: 'Random description Three'},
  {id: 16, image: 'https://s3-us-west-2.amazonaws.com/nadm2.bodiewebdesign.com/photos/intro16.jpg', alt: 'Indiana', title: 'Passing by Lake Michigan in Indiana', description: 'Random description Four'},
  {id: 17, image: 'https://s3-us-west-2.amazonaws.com/nadm2.bodiewebdesign.com/photos/intro17.jpg', alt: 'Jenn and Adam', title: 'Long plane rides make you Crazy', description: 'Random description One'},
  {id: 18, image: 'https://s3-us-west-2.amazonaws.com/nadm2.bodiewebdesign.com/photos/intro18.jpg', alt: 'Ohio & West Virginia', title: 'The Ohio River cutting through Ohio and West Virginia', description: 'Random description Two'},
  {id: 19, image: 'https://s3-us-west-2.amazonaws.com/nadm2.bodiewebdesign.com/photos/intro19.jpg', alt: 'Uniontown', title: 'Uniontown, Pennsylvania', description: 'Random description Three'},
  {id: 20, image: 'https://s3-us-west-2.amazonaws.com/nadm2.bodiewebdesign.com/photos/intro20.jpg', alt: 'Jenn & Adam', title: 'We\'re ready for this plane to land', description: 'Random description Four'},        
];

export const BALTIMOREPICTURES: Picture[] = [
    {id: 1, image: 'baltimore1.jpg', alt: 'MT&T Bank Stadium', title: 'MT&T Bank Stadium', description: 'Home of the Baltimore Ravens'},
    {id: 2, image: 'baltimore2.jpg', alt: 'MT&T Bank Stadium', title: 'MT&T Bank Stadium', description: 'I finally got a picture of the football stadium'},
    {id: 3, image: 'baltimore3.jpg', alt: 'Baltimore', title: 'Welcome Back Baltimore', description: 'At least there\'s no Snow'},
    {id: 4, image: 'baltimore4.jpg', alt: 'Baltimore', title: 'Shake Shack', description: ''},
    {id: 5, image: 'baltimore5.jpg', alt: 'Baltimore World Trade Center', title: 'Baltimore World Trade Center', description: '9/11 Memorial'},
    {id: 6, image: 'baltimore6.jpg', alt: 'Baltimore Skyline', title: 'Baltimore Skyline', description: ''},
    {id: 7, image: 'baltimore7.jpg', alt: 'Chesapeake Ship', title: 'Chesapeake Ship', description: ''},
    {id: 8, image: 'baltimore8.jpg', alt: 'Chesapeake Ship', title: 'Chesapeake Ship', description: ''},
    {id: 9, image: 'baltimore9.jpg', alt: 'Inner Harbor', title: 'The Other Side of the Inner Harbor', description: ''},
    {id: 10, image: 'baltimore10.jpg', alt: 'National Aquarium', title: 'National Aquarium', description: ''},
    {id: 11, image: 'baltimore11.jpg', alt: 'National Aquarium', title: 'National Aquarium', description: ''},
    {id: 12, image: 'baltimore12.jpg', alt: 'Baltimore World Trade Center', title: 'Baltimore World Trade Center', description: ''},
    {id: 13, image: 'baltimore13.jpg', alt: 'Baltimore World Trade Center', title: 'Baltimore World Trade Center', description: ''},
    {id: 14, image: 'baltimore14.jpg', alt: 'Baltimore Skyline', title: 'Baltimore Skyline', description: ''},
    {id: 15, image: 'baltimore15.jpg', alt: 'Baltimore World Trade Center', title: 'Baltimore World Trade Center', description: ''},
    {id: 16, image: 'baltimore16.jpg', alt: 'Baltimore World Trade Center', title: 'Baltimore World Trade Center', description: ''},
    {id: 17, image: 'baltimore17.jpg', alt: 'National Aquarium from across the Harbor', title: 'National Aquarium from across the Harbor', description: ''},
    {id: 18, image: 'baltimore18.jpg', alt: 'U.S.S. Constellation', title: 'U.S.S. Constellation', description: ''},
    {id: 19, image: 'baltimore19.jpg', alt: 'U.S.S. Constellation', title: 'Anchor at U.S.S. Constellation', description: ''},
    {id: 20, image: 'baltimore20.jpg', alt: 'View from the Inner Harbor', title: 'View from the Inner Harbor', description: ''},
    {id: 21, image: 'baltimore21.jpg', alt: 'View from the Inner Harbor', title: 'View from the Inner Harbor', description: ''},
    {id: 22, image: 'baltimore22.jpg', alt: 'U.S.S. Constellation Museum', title: 'U.S.S. Constellation Museum', description: ''},
    {id: 23, image: 'baltimore23.jpg', alt: 'Baltimore Skyline', title: 'Baltimore Skyline', description: 'The Transamerica Tower, located on the far left, is the tallest building in Baltimore (and Maryland) at 529 feet'},
    {id: 24, image: 'baltimore24.jpg', alt: 'View from the Inner Harbor', title: 'View from the Inner Harbor', description: 'I love this view!'},
    {id: 25, image: 'baltimore25.jpg', alt: 'Jenn', title: 'Stand Proud, Jenn', description: ''},
    {id: 26, image: 'baltimore26.jpg', alt: 'Jenn', title: 'Another great picture of Jenn', description: ''},
    {id: 27, image: 'baltimore27.jpg', alt: 'Jenn', title: 'I Pledge the Alligence, to the Flag', description: ''},
    {id: 28, image: 'baltimore28.jpg', alt: 'Adam and Jenn', title: 'Adam taking a selfie of Jenn pledging the alligence', description: ''},
    {id: 29, image: 'baltimore29.jpg', alt: 'View from the Inner Harbor', title: 'View from the Inner Harbor', description: ''},
    {id: 30, image: 'baltimore30.jpg', alt: 'Baltimore World Trade Center', title: 'Baltimore World Trade Center', description: ''},
    {id: 31, image: 'baltimore31.jpg', alt: 'Jenn', title: 'Jenn at a different angle', description: 'Nice picture Neal'},
    {id: 32, image: 'baltimore32.jpg', alt: 'Adam', title: 'Captain Adam\'s Happy', description: ''},
    {id: 33, image: 'baltimore33.jpg', alt: 'Adam', title: 'On Top of the World', description: ''},
    {id: 34, image: 'baltimore34.jpg', alt: 'Adam and Jenn', title: 'Adam and Jenn', description: ''},
    {id: 35, image: 'baltimore35.jpg', alt: 'Adam and Jenn', title: 'Same Picture, different View', description: ''},
    {id: 36, image: 'baltimore36.jpg', alt: 'U.S.S. Constellation', title: 'U.S.S. Constellation', description: ''},
    {id: 37, image: 'baltimore37.jpg', alt: 'Jenn and Neal', title: 'Smile Neal', description: ''},
    {id: 38, image: 'baltimore38.jpg', alt: 'Jenn and Neal', title: 'Please Smile Neal', description: ''},
    {id: 39, image: 'baltimore39.jpg', alt: 'Jenn and Neal', title: 'That\'s not a Smile Neal', description: ''},
    {id: 40, image: 'baltimore40.jpg', alt: 'Jenn and Neal', title: 'Side View, still no Smile Neal', description: ''},
    {id: 41, image: 'baltimore41.jpg', alt: 'Jenn and Neal', title: 'Adam taking a picture of Neal taking a selfie of him and Jenn', description: ''},
    {id: 42, image: 'baltimore42.jpg', alt: 'Jenn and Neal', title: 'Almost there, Neal', description: ''},
    {id: 43, image: 'baltimore43.jpg', alt: 'Jenn and Neal', title: 'That\'s more like it, Neal', description: ''},
    {id: 44, image: 'baltimore44.jpg', alt: 'Jenn and Neal', title: 'Time for a Piggyback Ride', description: ''},
    {id: 45, image: 'baltimore45.jpg', alt: 'Baltimore Skyline', title: 'Baltimore Skyline', description: 'The second to the left prominent building, 100 East Pratt Street is the fifth tallest in the state.'},
    {id: 46, image: 'baltimore46.jpg', alt: 'U.S.S. Constellation', title: 'U.S.S. Constellation', description: ''},
    {id: 47, image: 'baltimore47.jpg', alt: 'U.S.S. Constellation', title: 'U.S.S. Constellation', description: ''},
    {id: 48, image: 'baltimore48.jpg', alt: 'U.S.S. Constellation', title: 'U.S.S. Constellation', description: ''},
    {id: 49, image: 'baltimore49.jpg', alt: 'Ripley\'s Believe it Or Not Odditorium', title: 'Ripley\'s Believe it Or Not Odditorium', description: ''},
    {id: 50, image: 'baltimore50.jpg', alt: 'U.S.S. Constellation', title: 'U.S.S. Constellation', description: ''},
    {id: 51, image: 'baltimore51.jpg', alt: 'View from the Inner Harbor', title: 'View from the Inner Harbor', description: ''},
    {id: 52, image: 'baltimore52.jpg', alt: 'Hebrew', title: 'Hebrew on the Streets', description: 'Jenn found this, good eye!'},
    {id: 53, image: 'baltimore53.jpg', alt: 'Baltimore World Trade Center', title: 'Baltimore World Center', description: ''},
    {id: 54, image: 'baltimore54.jpg', alt: 'Baltimore Skyline', title: 'Baltimore Skyline', description: 'The second tallest building in Maryland, the Bank of America Building, is on the right with the bright yellow top'},
    {id: 55, image: 'baltimore55.jpg', alt: 'Baltimore Skyline', title: 'Baltimore Skyline', description: ''},
    {id: 56, image: 'baltimore56.jpg', alt: 'Baltimore Skyline', title: 'Baltimore Skyline', description: ''},
    {id: 57, image: 'baltimore57.jpg', alt: 'Baltimore Skyline', title: 'Baltimore Skyline', description: ''},
    {id: 58, image: 'baltimore58.jpg', alt: '', title: '', description: ''}                               
]

export const PIERPICTURES: Picture[] = [
    {id: 1, image: 'pier1.jpg', alt: 'Hard Rock Cafe', title: 'Hard Rock Cafe', description: ''},
    {id: 2, image: 'pier2.jpg', alt: 'Harbor', title: 'Harbor from the Pier', description: ''},
    {id: 3, image: 'pier3.jpg', alt: 'Phillips', title: 'Phillips Seafood', description: ''},
    {id: 4, image: 'pier4.jpg', alt: 'Jenn', title: 'Smile Jenn', description: ''},
    {id: 5, image: 'pier5.jpg', alt: 'Jenn', title: 'Not a Promotion of Barnes & Noble', description: ''},
    {id: 6, image: 'pier6.jpg', alt: 'Jenn', title: 'Jenn laughing', description: ''},
    {id: 7, image: 'pier7.jpg', alt: 'Pier 4', title: 'Pier 4', description: ''},
    {id: 8, image: 'pier8.jpg', alt: 'Adam', title: 'Selfie Time!', description: ''},
    {id: 9, image: 'pier9.jpg', alt: 'Dick\'s Last Resort', title: 'Dick\'s Last Resort', description: ''},
    {id: 10, image: 'pier10.jpg', alt: 'Grumpy', title: 'We\'re both Grumpy!', description: ''},
    {id: 11, image: 'pier11.jpg', alt: 'Pier 4', title: 'Pier 4', description: ''},
    {id: 12, image: 'pier12.jpg', alt: 'Fish', title: 'Fish', description: ''},  
    {id: 13, image: 'pier13.jpg', alt: 'Adam', title: 'Smile Adam!', description: ''},
    {id: 14, image: 'pier14.jpg', alt: 'View from the Pier', title: 'View from the Pier', description: ''},
    {id: 15, image: 'pier15.jpg', alt: 'View from the Pier', title: 'View from the Pier', description: ''}                
]

/*    {id: , image: '.jpg', alt: '', title: '', description: ''},*/