import { Picture } from './picture';

export const INTROPICTURES: Picture[] = [
  {id: 1, image: 'intro1.jpg', alt: 'Portland', title: 'Goodbye Portland'},
  {id: 2, image: 'intro2.jpg', alt: 'Above the Clouds', title: 'Cloudy Portland'},
  {id: 3, image: 'intro3.jpg', alt: 'Mt. St. Helens and Mt. Rainier', title: 'Mt. St. Helens and Mt. Rainier above the Clouds'},
  {id: 4, image: 'intro4.jpg', alt: 'Mt. Adams', title: 'Mt. Adams dominating the view'},
  {id: 5, image: 'intro5.jpg', alt: 'Columbia River', title: 'Look at all them circles'},
  {id: 6, image: 'intro6.jpg', alt: 'Columbia River', title: 'Even more circles'},
  {id: 7, image: 'intro7.jpg', alt: 'Columbia River', title: 'Circles with a dam'},
  {id: 8, image: 'intro8.jpg', alt: 'Bozeman', title: 'Flying over Bozeman'},
  {id: 9, image: 'intro9.jpg', alt: 'Bozeman', title: 'Goodbye Bozeman'},
  {id: 10, image: 'intro10.jpg', alt: 'Montana', title: 'Crazy Clouds'},
  {id: 11, image: 'intro11.jpg', alt: 'Montana', title: 'Is that a Horse?'},
  {id: 12, image: 'intro12.jpg', alt: 'Montana', title: 'More Crazy clouds'},
  {id: 13, image: 'intro13.jpg', alt: 'Illinois', title: 'Approaching Chicagoland'},
  {id: 14, image: 'intro14.jpg', alt: 'Illinois', title: 'Plentiful of Clouds near Chicagoland'},
  {id: 15, image: 'intro15.jpg', alt: 'Illinois', title: 'More crazy clouds near Chicagoland'},
  {id: 16, image: 'intro16.jpg', alt: 'Indiana', title: 'Passing by Lake Michigan in Indiana'},
  {id: 17, image: 'intro17.jpg', alt: 'Jenn and Adam', title: 'Long plane rides make you Crazy'},
  {id: 18, image: 'intro18.jpg', alt: 'Ohio & West Virginia', title: 'The Ohio River cutting through Ohio and West Virginia'},
  {id: 19, image: 'intro19.jpg', alt: 'Uniontown', title: 'Uniontown, Pennsylvania'},
  {id: 20, image: 'intro20.jpg', alt: 'Jenn & Adam', title: 'We\'re ready for this plane to land'},  
  {id: 21, image: 'laurel1.jpg', alt: 'Laurel', title: 'View from the Hotel'},
  {id: 22, image: 'laurel2.jpg', alt: 'Sunset', title: 'Sunset in Laurel'},
  {id: 23, image: 'laurel3.jpg', alt: 'Sunset', title: 'Sunset in Laurel'},
  {id: 24, image: 'laurel4.jpg', alt: 'Jenn and Neal', title: 'Two Deaths and a Chiropractic Treatment'},
  {id: 25, image: 'laurel5.jpg', alt: 'Jenn and Neal', title: 'Coming to a Hotel Room Near You'},
  {id: 26, image: 'laurel6.jpg', alt: 'Jenn and Neal', title: 'This is not part of the cirriculum'},
  {id: 27, image: 'laurel7.jpg', alt: 'Holiday Inn Express', title: 'Holiday Inn Express'}                    
];

export const BALTIMOREPICTURES: Picture[] = [
    {id: 1, image: 'baltimore1.jpg', alt: 'MT&T Bank Stadium', title: 'MT&T Bank Stadium', description: 'Home of the Baltimore Ravens'},
    {id: 2, image: 'baltimore2.jpg', alt: 'MT&T Bank Stadium', title: 'MT&T Bank Stadium', description: 'I finally got a picture of the football stadium'},
    {id: 3, image: 'baltimore3.jpg', alt: 'Baltimore', title: 'Welcome Back Baltimore', description: 'At least there\'s no Snow'},
    {id: 4, image: 'baltimore4.jpg', alt: 'Baltimore', title: 'Shake Shack'},
    {id: 5, image: 'baltimore5.jpg', alt: 'Baltimore World Trade Center', title: 'Baltimore World Trade Center', description: '9/11 Memorial'},
    {id: 6, image: 'baltimore6.jpg', alt: 'Baltimore Skyline', title: 'Baltimore Skyline'},
    {id: 7, image: 'baltimore7.jpg', alt: 'Chesapeake Ship', title: 'Chesapeake Ship'},
    {id: 8, image: 'baltimore8.jpg', alt: 'Chesapeake Ship', title: 'Chesapeake Ship'},
    {id: 9, image: 'baltimore9.jpg', alt: 'Inner Harbor', title: 'The Other Side of the Inner Harbor'},
    {id: 10, image: 'baltimore10.jpg', alt: 'National Aquarium', title: 'National Aquarium'},
    {id: 11, image: 'baltimore11.jpg', alt: 'National Aquarium', title: 'National Aquarium'},
    {id: 12, image: 'baltimore12.jpg', alt: 'Baltimore World Trade Center', title: 'Baltimore World Trade Center'},
    {id: 13, image: 'baltimore13.jpg', alt: 'Baltimore World Trade Center', title: 'Baltimore World Trade Center'},
    {id: 14, image: 'baltimore14.jpg', alt: 'Baltimore Skyline', title: 'Baltimore Skyline'},
    {id: 15, image: 'baltimore15.jpg', alt: 'Baltimore World Trade Center', title: 'Baltimore World Trade Center'},
    {id: 16, image: 'baltimore16.jpg', alt: 'Baltimore World Trade Center', title: 'Baltimore World Trade Center'},
    {id: 17, image: 'baltimore17.jpg', alt: 'National Aquarium from across the Harbor', title: 'National Aquarium from across the Harbor'},
    {id: 18, image: 'baltimore18.jpg', alt: 'U.S.S. Constellation', title: 'U.S.S. Constellation'},
    {id: 19, image: 'baltimore19.jpg', alt: 'U.S.S. Constellation', title: 'Anchor at U.S.S. Constellation'},
    {id: 20, image: 'baltimore20.jpg', alt: 'View from the Inner Harbor', title: 'View from the Inner Harbor'},
    {id: 21, image: 'baltimore21.jpg', alt: 'View from the Inner Harbor', title: 'View from the Inner Harbor'},
    {id: 22, image: 'baltimore22.jpg', alt: 'U.S.S. Constellation Museum', title: 'U.S.S. Constellation Museum'},
    {id: 23, image: 'baltimore23.jpg', alt: 'Baltimore Skyline', title: 'Baltimore Skyline', description: 'The Transamerica Tower, located on the far left, is the tallest building in Baltimore (and Maryland) at 529 feet'},
    {id: 24, image: 'baltimore24.jpg', alt: 'View from the Inner Harbor', title: 'View from the Inner Harbor', description: 'I love this view!'},
    {id: 25, image: 'baltimore25.jpg', alt: 'Jenn', title: 'Stand Proud, Jenn'},
    {id: 26, image: 'baltimore26.jpg', alt: 'Jenn', title: 'Another great picture of Jenn'},
    {id: 27, image: 'baltimore27.jpg', alt: 'Jenn', title: 'I Pledge the Alligence, to the Flag'},
    {id: 28, image: 'baltimore28.jpg', alt: 'Adam and Jenn', title: 'Adam taking a selfie of Jenn pledging the alligence'},
    {id: 29, image: 'baltimore29.jpg', alt: 'View from the Inner Harbor', title: 'View from the Inner Harbor'},
    {id: 30, image: 'baltimore30.jpg', alt: 'Baltimore World Trade Center', title: 'Baltimore World Trade Center'},
    {id: 31, image: 'baltimore31.jpg', alt: 'Jenn', title: 'Jenn at a different angle', description: 'Nice picture Neal'},
    {id: 32, image: 'baltimore32.jpg', alt: 'Adam', title: 'Captain Adam\'s Happy'},
    {id: 33, image: 'baltimore33.jpg', alt: 'Adam', title: 'On Top of the World'},
    {id: 34, image: 'baltimore34.jpg', alt: 'Adam and Jenn', title: 'Adam and Jenn'},
    {id: 35, image: 'baltimore35.jpg', alt: 'Adam and Jenn', title: 'Same Picture, different View'},
    {id: 36, image: 'baltimore36.jpg', alt: 'U.S.S. Constellation', title: 'U.S.S. Constellation'},
    {id: 37, image: 'baltimore37.jpg', alt: 'Jenn and Neal', title: 'Smile Neal'},
    {id: 38, image: 'baltimore38.jpg', alt: 'Jenn and Neal', title: 'Please Smile Neal'},
    {id: 39, image: 'baltimore39.jpg', alt: 'Jenn and Neal', title: 'That\'s not a Smile Neal'},
    {id: 40, image: 'baltimore40.jpg', alt: 'Jenn and Neal', title: 'Side View, still no Smile Neal'},
    {id: 41, image: 'baltimore41.jpg', alt: 'Jenn and Neal', title: 'Adam taking a picture of Neal taking a selfie of him and Jenn'},
    {id: 42, image: 'baltimore42.jpg', alt: 'Jenn and Neal', title: 'Almost there, Neal'},
    {id: 43, image: 'baltimore43.jpg', alt: 'Jenn and Neal', title: 'That\'s more like it, Neal'},
    {id: 44, image: 'baltimore44.jpg', alt: 'Jenn and Neal', title: 'Time for a Piggyback Ride'},
    {id: 45, image: 'baltimore45.jpg', alt: 'Baltimore Skyline', title: 'Baltimore Skyline', description: 'The second to the left prominent building, 100 East Pratt Street is the fifth tallest in the state.'},
    {id: 46, image: 'baltimore46.jpg', alt: 'U.S.S. Constellation', title: 'U.S.S. Constellation'},
    {id: 47, image: 'baltimore47.jpg', alt: 'U.S.S. Constellation', title: 'U.S.S. Constellation'},
    {id: 48, image: 'baltimore48.jpg', alt: 'U.S.S. Constellation', title: 'U.S.S. Constellation'},
    {id: 49, image: 'baltimore49.jpg', alt: 'Ripley\'s Believe it Or Not Odditorium', title: 'Ripley\'s Believe it Or Not Odditorium'},
    {id: 50, image: 'baltimore50.jpg', alt: 'U.S.S. Constellation', title: 'U.S.S. Constellation'},
    {id: 51, image: 'baltimore51.jpg', alt: 'View from the Inner Harbor', title: 'View from the Inner Harbor'},
    {id: 52, image: 'baltimore52.jpg', alt: 'Hebrew', title: 'Hebrew on the Streets', description: 'Jenn found this, good eye!'},
    {id: 53, image: 'baltimore53.jpg', alt: 'Baltimore World Trade Center', title: 'Baltimore World Trade Center'},
    {id: 54, image: 'baltimore54.jpg', alt: 'Baltimore Skyline', title: 'Baltimore Skyline', description: 'The second tallest building in Maryland, the Bank of America Building, is on the right with the bright yellow top'},
    {id: 55, image: 'baltimore55.jpg', alt: 'Baltimore Skyline', title: 'Baltimore Skyline'},
    {id: 56, image: 'baltimore56.jpg', alt: 'Baltimore Skyline', title: 'Baltimore Skyline'},
    {id: 57, image: 'baltimore57.jpg', alt: 'Baltimore Skyline', title: 'Baltimore Skyline'},
    {id: 58, image: 'baltimore58.jpg', alt: 'Baltimore Skyline', title: 'Baltimore SKyline'}                               
]

export const PIERPICTURES: Picture[] = [
    {id: 1, image: 'pier1.jpg', alt: 'Hard Rock Cafe', title: 'Hard Rock Cafe'},
    {id: 2, image: 'pier2.jpg', alt: 'Harbor', title: 'Harbor from the Pier'},
    {id: 3, image: 'pier3.jpg', alt: 'Phillips', title: 'Phillips Seafood'},
    {id: 4, image: 'pier4.jpg', alt: 'Jenn', title: 'Smile Jenn'},
    {id: 5, image: 'pier5.jpg', alt: 'Jenn', title: 'Not a Promotion of Barnes & Noble'},
    {id: 6, image: 'pier6.jpg', alt: 'Jenn', title: 'Jenn laughing'},
    {id: 7, image: 'pier7.jpg', alt: 'Pier 4', title: 'Pier 4'},
    {id: 8, image: 'pier8.jpg', alt: 'Adam', title: 'Selfie Time!'},
    {id: 9, image: 'pier9.jpg', alt: 'Dick\'s Last Resort', title: 'Dick\'s Last Resort'},
    {id: 10, image: 'pier10.jpg', alt: 'Grumpy', title: 'We\'re both Grumpy!'},
    {id: 11, image: 'pier11.jpg', alt: 'Pier 4', title: 'Pier 4'},
    {id: 12, image: 'pier12.jpg', alt: 'Fish', title: 'Fish'},  
    {id: 13, image: 'pier13.jpg', alt: 'Adam', title: 'Smile Adam!'},
    {id: 14, image: 'pier14.jpg', alt: 'View from the Pier', title: 'View from the Pier'},
    {id: 15, image: 'pier15.jpg', alt: 'View from the Pier', title: 'View from the Pier'}                
]

export const KEVINPICTURES: Picture[] = [
  {id: 1, image: 'kevin1.jpg', alt: 'Pho Kevin', title: 'Pho Kevin'},
  {id: 2, image: 'kevin2.jpg', alt: 'Thai Iced Tea', title: 'Thai Iced Tea'},
  {id: 3, image: 'kevin3.jpg', alt: 'Pho', title: 'Pho'}  
]

export const DINERPICTURES: Picture[] = [
  {id: 1, image: 'silver-diner1.jpg', alt: 'Silver Diner', title: 'Silver Diner'},
  {id: 2, image: 'silver-diner2.jpg', alt: 'Jenn', title: 'Smile Jenn'},
  {id: 3, image: 'silver-diner3.jpg', alt: 'Jenn', title: 'Is that Yummy Jenn?'},
  {id: 4, image: 'silver-diner4.jpg', alt: 'Wasabi Salmon Sliders', title: 'Wasabi Salmon Sliders'},  
]

export const MARYLANDPICTURES: Picture[] = [
{id: 1, image: 'maryland1.jpg', alt: 'Cruise Ship', title: 'Cruise Ship Past Baltimore'},
{id: 2, image: 'maryland2.jpg', alt: 'Susquehanna River', title: 'Over the Susquehanna River in Havre de Grace'},
{id: 3, image: 'maryland3.jpg', alt: 'Adam', title: 'Car Selfie'},
{id: 4, image: 'maryland4.jpg', alt: 'Susquehanna River', title: 'Same Susquehanna River, but during a Sunset'},
{id: 5, image: 'maryland5.jpg', alt: 'Baltimore', title: 'Baltimore from a distance during the Evening'},
{id: 6, image: 'maryland6.jpg', alt: 'Blobs Road', title: 'Blobs Road.  Really?'},
]

export const DELAWAREPICTURES: Picture[] = [
{id: 1, image: 'delaware1.jpg', alt: 'Delaware', title: 'Welcome to Delaware', description: 'At least they\'re a Blue State'},
{id: 2, image: 'delaware2.jpg', alt: 'Delaware', title: 'We\'re approaching Philadelphia', description: 'and Wilmington, too...'},
{id: 3, image: 'delaware3.jpg', alt: 'Delaware', title: 'Newport Closed'},
{id: 4, image: 'delaware4.jpg', alt: 'Delaware', title: 'Crossing the Christina River'},
{id: 5, image: 'delaware5.jpg', alt: 'Wilimgton', title: 'The view of Wilmington...and Neal\'s watch'},
{id: 6, image: 'delaware6.jpg', alt: 'Delaware', title: 'Another ordinary Delaware Picture'},
{id: 7, image: 'delaware7.jpg', alt: 'Adam', title: 'Tilted Mirror in a Dunkin Donuts Bathroom'},
{id: 8, image: 'delaware8.jpg', alt: 'Claymont', title: 'Claymont Fire Station'},
{id: 9, image: 'delaware9.jpg', alt: 'Adam', title: 'My "I\'m in Delaware" Picture'}

]

export const PHILADELPHIAWELCOMEPICTURES: Picture[] = [
{id: 1, image: 'philadelphia1.jpg', alt: 'Pennsylvania', title: 'Welcome to Pennsylvania', description: 'Nice to meet you'},
{id: 2, image: 'philadelphia4.jpg', alt: 'United States Coast Guard', title: 'United States Coast Guard'},
{id: 3, image: 'philadelphia5.jpg', alt: 'Municipal Pier', title: 'Municipal Pier'},
{id: 4, image: 'philadelphia6.jpg', alt: 'Merchants Exchange Building', title: 'Merchants Exchange Building'},
{id: 5, image: 'philadelphia7.jpg', alt: 'Museum of the American Revolution', title: 'Museum of the American Revolution'},
{id: 6, image: 'philadelphia8.jpg', alt: 'Colonial', title: 'Woman knitting in Colonial clothing'},
{id: 7, image: 'philadelphia9.jpg', alt: 'Philadelphia', title: 'Philadelphia', description: 'View from the parking garage'},
{id: 8, image: 'philadelphia10.jpg', alt: 'Chestnut Street', title: 'Chestnut Street'},
{id: 9, image: 'philadelphia11.jpg', alt: 'Chestnut Street', title: 'Chestnut Street'},
{id: 10, image: 'philadelphia12.jpg', alt: 'Market Street', title: 'Market Street'},
{id: 11, image: 'philadelphia13.jpg', alt: 'Market Street', title: 'Market Street'},
{id: 12, image: 'philadelphia14.jpg', alt: 'Rainbow', title: 'Man wearing nothing but Rainbow Underwear', description: 'Neal likes the view'},
{id: 13, image: 'philadelphia15.jpg', alt: 'Big Ass', title: 'Big Ass Slices'},
{id: 14, image: 'philadelphia16.jpg', alt: 'Bodine Street', title: 'Bodine Street', description: 'The closest to Bodie we\'ll see in Philly'},
{id: 15, image: 'philadelphia17.jpg', alt: 'Love Wins', title: 'Love Wins', description: 'Damn Right!'},
{id: 16, image: 'philadelphia18.jpg', alt: 'United States Post Office', title: 'United States Post Office', description: 'Part of the Ben Franklin Museum'},
{id: 17, image: 'philadelphia19.jpg', alt: 'Printing Office', title: 'Printing Office & Bindery'},
{id: 18, image: 'philadelphia20.jpg', alt: 'National Museum of American Jewish History', title: 'National Museum of American Jewish History'}
]


export const INDEPENDENCEPICTURES: Picture[] = [
{id: 1, image: 'independence1.jpg', alt: 'Independence National Historical Park', title: 'Independence National Historical Park'},
{id: 2, image: 'independence2.jpg', alt: 'Independence National Historical Park', title: 'Independence National Historical Park'},
{id: 3, image: 'independence3.jpg', alt: 'Independence Hall', title: 'Independence Hall', description: 'Where the Declaration of Independence was signed'},
{id: 4, image: 'independence4.jpg', alt: 'Independence Hall', title: 'Independence Hall'},
{id: 5, image: 'independence5.jpg', alt: 'Independence Hall', title: 'Independence Hall'},
{id: 6, image: 'independence6.jpg', alt: 'Independence Hall', title: 'Independence Hall', description: 'Also the site of the 1915 convention that lead to the formation of the League to Enforce Peace, which eventually became the United Nations.'},
{id: 7, image: 'independence7.jpg', alt: 'Liberty Bell Center', title: 'Liberty Bell Center'},
{id: 8, image: 'independence8.jpg', alt: 'Independence National Historical Park', title: 'Independence National Historical Park'},
{id: 9, image: 'independence10.jpg', alt: 'Adam', title: 'Independence Selfie'},
{id: 10, image: 'independence11.jpg',  alt: 'Independence Hall', title: 'Independence Hall'},
{id: 11, image: 'independence12.jpg',  alt: 'Liberty Bell Center', title: 'Liberty Bell Center'},
{id: 12, image: 'independence13.jpg',  alt: 'Adam', title: 'Adam at Independence Historical National Park'},
{id: 13, image: 'independence14.jpg',  alt: 'Liberty Bell Center', title: 'Liberty Bell Center'},
{id: 14, image: 'independence15.jpg',  alt: 'Independence Hall', title: 'Independence Hall'},
{id: 15, image: 'independence17.jpg',  alt: 'Follow the Steps', title: 'Follow the Steps'},
{id: 16, image: 'independence18.jpg',  alt: 'Independence National Historical Park', title: 'No Bigotry at the Independence National Historical Park'},
{id: 17, image: 'independence19.jpg',  alt: 'Independence Visitor Center', title: 'Independence Visitor Center'},
{id: 18, image: 'independence20.jpg', alt: 'Independence National Historical Park', title: 'Independence National Historical Park'},
{id: 19, image: 'independence21.jpg',  alt: 'Independence National Historical Park', title: 'Independence National Historical Park'},
{id: 20, image: 'philadelphia21.jpg', alt: 'A Rocky Statue', title: 'A Rocky Statue, not The Rocky Statue'},
{id: 21, image: 'philadelphia22.jpg', alt: 'Adam', title: 'Adam with a Rocky Statue'},
]

export const LIBERTYBELLPICTURES: Picture[] = [
{id: 1, image: 'liberty-bell1.jpg', alt: 'In Line for the Liberty Bell', title: 'In Line for the Liberty Bell'},
{id: 2, image: 'liberty-bell2.jpg', alt: 'In Line for the Liberty Bell', title: 'In Line for the Liberty Bell'},
{id: 3, image: 'liberty-bell3.jpg', alt: 'Adam', title: 'Adam In Line for the Liberty Bell'},
{id: 4, image: 'liberty-bell4.jpg', alt: 'In Line for the Liberty Bell', title: 'In Line for the Liberty Bell'},
{id: 5, image: 'liberty-bell5.jpg', alt: 'In Line for the Liberty Bell', title: 'In Line for the Liberty Bell'},
{id: 6, image: 'liberty-bell6.jpg', alt: 'In Line for the Liberty Bell', title: 'In Line for the Liberty Bell'},
{id: 7, image: 'liberty-bell7.jpg', alt: 'Adam', title: 'In Line for the Liberty Bell'},
{id: 8, image: 'liberty-bell8.jpg', alt: 'In Line for the Liberty Bell', title: 'In Line for the Liberty Bell'},
{id: 9, image: 'liberty-bell9.jpg', alt: 'Memorial', title: 'Memorial', description: 'I miss Obama, we need an Actual President, not a clown'},
{id: 10, image: 'liberty-bell10.jpg', alt: 'In Line for the Liberty Bell', title: 'In Line for the Liberty Bell'},
{id: 11, image: 'liberty-bell11.jpg', alt: 'In Line for the Liberty Bell', title: 'In Line for the Liberty Bell'},
{id: 12, image: 'liberty-bell12.jpg', alt: 'Inside the Line for the Liberty Bell', title: 'Inside the Line for the Liberty Bell'},
{id: 13, image: 'liberty-bell13.jpg', alt: 'Inside the Line for the Liberty Bell', title: 'Inside the Line for the Liberty Bell'},
{id: 14, image: 'liberty-bell14.jpg', alt: 'Inside the Line for the Liberty Bell', title: 'Inside the Line for the Liberty Bell'},
{id: 15, image: 'liberty-bell15.jpg', alt: 'Inside the Line for the Liberty Bell', title: 'Inside the Line for the Liberty Bell'},
{id: 16, image: 'liberty-bell16.jpg', alt: 'Inside the Line for the Liberty Bell', title: 'Inside the Line for the Liberty Bell'},
{id: 17, image: 'liberty-bell17.jpg', alt: 'Inside the Liberty Bell Center, Metal Detector', title: 'Inside the Liberty Bell Center, Metal Detector'},
{id: 18, image: 'liberty-bell18.jpg', alt: 'America\'s Liberty Bell', title: 'America\'s Liberty Bell'},
{id: 19, image: 'liberty-bell19.jpg', alt: 'The World\'s Symbol for Liberty', title: 'The World\'s Symbol for Liberty'},
{id: 20, image: 'liberty-bell20.jpg', alt: 'Inside the Liberty Bell Center', title: 'Inside the Liberty Bell Center'},
{id: 21, image: 'liberty-bell21.jpg', alt: 'The Liberty Bell', title: 'The Liberty Bell'},
{id: 22, image: 'liberty-bell22.jpg', alt: 'Adam', title: 'Adam at Liberty Bell'},
{id: 23, image: 'liberty-bell23.jpg', alt: 'Adam', title: 'Adam at Liberty Bell with better view'},
{id: 24, image: 'liberty-bell24.jpg', alt: 'Liberty Bell', title: 'Liberty Bell'},
{id: 25, image: 'liberty-bell25.jpg', alt: 'Independence Hall', title: 'Independence Hall'},
{id: 26, image: 'liberty-bell26.jpg', alt: 'Liberty Bell', title: 'Liberty Bell'},
{id: 27, image: 'liberty-bell27.jpg', alt: 'Outside the Liberty Bell Center', title: 'Outside the Liberty Bell Center'}
]

export const PRIDEPICTURES: Picture[] = [
{id: 1, image: 'pride1.jpg', alt: 'Judge\'s Booth', title: 'Judge\'s Booth'},
{id: 2, image: 'pride2.jpg', alt: 'Pride Parade', title: 'Getting ready for the Pride Parade'},
{id: 3, image: 'pride3.jpg', alt: 'First Amendment', title: 'The First Amendment: For All Americans, including the LGBTQ'},
{id: 4, image: 'pride4.jpg', alt: 'First Amendment', title: 'The First Amendment', description: 'Where people have the right to wear a shirt that says "Gay as Fuck"'},
{id: 5, image: 'pride5.jpg', alt: 'Motorcycles', title: 'Motorcycles'},
{id: 6, image: 'pride6.jpg', alt: 'Motorcycles', title: 'Motorcycles'},
{id: 7, image: 'pride7.jpg', alt: 'Pride Parade', title: 'Scenes from the Pride Parade'},
{id: 8, image: 'pride8.jpg', alt: 'March', title: 'The March Begins'},
{id: 9, image: 'pride9.jpg', alt: 'Jewish Support', title: 'Philadelphia\'s Jewish Community supports the LGBTQ'},
{id: 10, image: 'pride10.jpg', alt: 'Pride Parade', title: 'More people marching'},
{id: 11, image: 'pride11.jpg', alt: 'Donald Trump in Lipstick', title: 'Donald Trump in Lipstick', description: 'Fact: Donald Trump did not recognize June as LGBTQ Pride Month; so much for him liking the LGBTQ community'},
{id: 12, image: 'pride12.jpg', alt: 'Pride Parade', title: 'Parade Floats'},
{id: 13, image: 'pride13.jpg', alt: 'PECO Float', title: 'PECO Float'},
{id: 14, image: 'pride14.jpg', alt: 'Pride Parade', title: 'More Parade Pictures'},
{id: 15, image: 'pride15.jpg', alt: 'Pussy Power', title: 'Pussy Power coming through.'},
{id: 16, image: 'pride16.jpg', alt: 'Furry Mascot', title: 'Furry Mascot coming through'},
{id: 17, image: 'pride17.jpg', alt: 'Furry Mascot', title: 'Furry Mascot gives a High Five'},
{id: 18, image: 'pride18.jpg', alt: 'Xfinity', title: 'Comcast might be a terrible cable provider, but at least they support LGBTQ Pride'},
{id: 19, image: 'pride19.jpg', alt: 'More Marching', title: 'More Marching'},
{id: 20, image: 'pride20.jpg', alt: 'The City of Brotherly Love', title: 'The City of Brotherly Love'},
{id: 21, image: 'pride21.jpg', alt: 'More Pride', title: 'More Pride'},
{id: 22, image: 'pride22.jpg', alt: 'More Pride', title: 'More Pride'},
{id: 23, image: 'pride23.jpg', alt: 'The Crowd Goes On', title: 'The Crowd Goes On'},
{id: 24, image: 'pride24.jpg', alt: 'Driving Through the Parade', title: 'Driving Through the Parade', description: 'I love this view!'},
{id: 25, image: 'pride25.jpg', alt: 'The Rainbow Effect', title: 'The Rainbow Effect'},
{id: 26, image: 'pride26.jpg', alt: 'The Calm Before the Storm', title: 'The Calm Before the Storm'},
{id: 27, image: 'pride27.jpg', alt: 'The Judges Booth', title: 'The Judges Booth'},
{id: 28, image: 'pride28.jpg', alt: 'Waive them Flags', title: 'Waive them Flags'},
{id: 29, image: 'pride29.jpg', alt: 'Introducing...The Flaggots', title: 'Introducing...The Flaggots', description: 'The Nation\'s oldest LGBTQ flag group'},
{id: 30, image: 'pride30.jpg', alt: 'The Flaggots', title: 'The Flaggots'},
{id: 31, image: 'pride31.jpg', alt: 'The Flaggots', title: 'The Flaggots'},
{id: 32, image: 'pride32.jpg', alt: 'The Flaggots', title: 'The Flaggots'},
{id: 33, image: 'pride33.jpg', alt: 'The Flaggots', title: 'The Flaggots'},
{id: 34, image: 'pride34.jpg', alt: 'The Flaggots and Jenn', title: 'The Flaggots'},
{id: 35, image: 'pride35.jpg', alt: 'The Flaggots and Jenn', title: 'The Flaggots'},
{id: 36, image: 'pride36.jpg', alt: 'The Flaggots', title: 'The Flaggots'},
{id: 37, image: 'pride37.jpg', alt: 'The Flaggots', title: 'The Flaggots'},
{id: 38, image: 'pride38.jpg', alt: 'One Confused Person', title: 'One Confused Person'},
{id: 39, image: 'pride39.jpg', alt: 'Gays 4 Trump', title: 'Gays 4 Trump', description: 'Ironically wearing a mask of Hillary Clinton, who actually supports the LGBTQ unlike Trump who only pretended to like them for vote pandering'},
{id: 40, image: 'pride40.jpg', alt: 'Neal', title: 'While I was walking around and Jenn was couped up inside, Neal and Heidi stayed at their one spot the entire time'},
{id: 41, image: 'pride41.jpg', alt: 'Refuse Facism', title: 'Refuse Fascism, Drive out Trump & Pence', description: 'Neal took this picture, I didn\'t even see this sign.  But it\'s 100% true.'},
{id: 42, image: 'pennsylvania23.jpg', alt: 'Jenn', title: 'Jenn was staying cool inside during the parade'},
{id: 43, image: 'pennsylvania24.jpg', alt: 'Cappuccino', title: 'Gotta enjoy a Cappuccino'}
]

export const PENNPICTURES: Picture[] = [
{id: 1, image: 'philadelphia25.jpg', alt: 'National Museum of American Jewish History', title: 'National Museum of American Jewish History', description: 'Everyone should feel Welcomed'},
{id: 2, image: 'philadelphia26.jpg', alt: 'Interesting View', title: 'Interesting View'},
{id: 3, image: 'philadelphia27.jpg', alt: 'Doggie Style', title: 'Doggie Style', description: 'Another weird place we saw: Llama Tooth'},
{id: 4, image: 'penn1.jpg', alt: 'Penn\'s Landing', title: 'Penn\'s Landing'},
{id: 5, image: 'penn2.jpg', alt: 'Delaware River', title: 'Delaware River'},
{id: 6, image: 'penn3.jpg', alt: 'I see New Jersey', title: 'I see New Jersey'},
{id: 7, image: 'penn4.jpg', alt: 'Welcome to Penn\'s Landing', title: 'Welcome to Penn\'s Landing'},
{id: 8, image: 'penn5.jpg', alt: 'Skating Rink', title: 'Skating Rink'},
{id: 9, image: 'penn6.jpg', alt: 'Benjamin Franklin Bridge', title: 'Benjamin Franklin Bridge'},
{id: 10, image: 'penn7.jpg', alt: 'Philadelphia Skyline', title: 'Philadelphia Skyline'},
{id: 11, image: 'penn8.jpg', alt: 'Philadelphia Skyline', title: 'Philadelphia Skyline'},
{id: 12, image: 'penn9.jpg', alt: 'Adam', title: 'Adam with Beads'},
{id: 13, image: 'penn10.jpg', alt: 'Adam', title: 'Welcome to Penn\'s Landing, Adam'},
{id: 14, image: 'penn11.jpg', alt: 'Market Street', title: 'Market Street'},
{id: 15, image: 'penn12.jpg', alt: 'Old City', title: 'Old City'},
{id: 16, image: 'penn13.jpg', alt: 'Old City', title: 'Old City'}
]

export const CONTINENTALPICTURES: Picture[] = [
  {id: 1, image: 'continental1.jpg', alt: 'Continental', title: 'Continental'},
  {id: 2, image: 'continental2.jpg', alt: 'Adam', title: 'Adam'},
  {id: 3, image: 'continental3.jpg', alt: 'Korean Tacos', title: 'Korean Tacos'}  
]

export const ARTPICTURES: Picture[] = [
{id: 1, image: 'art1.jpg', alt: 'Philadelphia Museum of Art', title: 'Philadelphia Museum of Art'},
{id: 2, image: 'art2.jpg', alt: 'Philadelphia Skyline', title: 'Philadelphia Skyline'},
{id: 3, image: 'art3.jpg', alt: 'Rocky Statue', title: 'Rocky Statue', description: 'The Rocky Statue'},
{id: 4, image: 'art4.jpg', alt: 'The Rocky Steps', title: 'The Rocky Steps'},
{id: 5, image: 'art5.jpg', alt: 'Philadephia Museum of Art', title: 'Philadelphia Museum of Art'},
{id: 6, image: 'art6.jpg', alt: 'Philadelphia Skyline', title: 'Philadelphia Skyline'},
{id: 7, image: 'art37.jpg', alt: 'Jenn doesn\'t want her picture taken', title: 'Jenn doesn\'t want her picture taken'},
{id: 8, image: 'art38.jpg', alt: 'Jenn really doesn\'t want her picture taken', title: 'Jenn really doesn\'t want her picture taken'},
{id: 9, image: 'art7.jpg', alt: 'Philadelphia Museum of Art', title: 'Philadelphia Museum of Art after the Rocky Run'},
{id: 10, image: 'art8.jpg', alt: 'Philadelphia Skyline', title: 'Philadelphia Skyline'},
{id: 11, image: 'art9.jpg', alt: 'Adam', title: 'Adam Heart Philly'},
{id: 12, image: 'art10.jpg', alt: 'Adam and Jenn', title: 'Adam and Jenn'},
{id: 13, image: 'art11.jpg', alt: 'Neal, Adam and Jenn', title: 'Neal, Adam and Jenn do the full Rocky', description: 'Jenn only did half Rocky'},
{id: 14, image: 'art12.jpg', alt: 'Philadelphia Skyline', title: 'Philadelphia Skyline' , description: 'The tallest building in Philadelphia, and the state of Pennsylvania, is the Comcast Center, the tall building on the left, at 975 feet'},
{id: 15, image: 'art13.jpg', alt: 'Rocky Steps', title: 'Rocky Steps'},
{id: 16, image: 'art14.jpg', alt: 'Philadelphia Museum of Art', title: 'Philadelphia Museum of Art'},
{id: 17, image: 'art15.jpg', alt: 'Adam', title: 'Adam at the Philadelphia Museum of Art'},
{id: 18, image: 'art16.jpg', alt: 'Philadelphia Museum of Art', title: 'Philadelphia Museum of Art'},
{id: 19, image: 'art17.jpg', alt: 'Philadelphia Museum of Art', title: 'Philadelphia Museum of Art Fountain'},
{id: 20, image: 'art18.jpg', alt: 'Jenn and Neal', title: 'Jenn and Neal'},
{id: 21, image: 'art19.jpg', alt: 'Adam', title: 'Adam wins!'},
{id: 22, image: 'art39.jpg', alt: 'Neal and Heidi', title: 'Neal and Heidi'},
{id: 23, image: 'art20.jpg', alt: 'Fountain', title: 'Fountain'},
{id: 24, image: 'art21.jpg', alt: 'Philadelphia Museum of Art', title: 'Philadelphia Museum of Art'},
{id: 25, image: 'art22.jpg', alt: 'Philadelphia Skyline', title: 'Philadelphia Skyline', description: 'The tall building to the right is the Comcast Technology Center, which will be the tallest building in Philadelphia once completed in 2018, at 1,121 feet'},
{id: 26, image: 'art23.jpg', alt: 'Philadelphia Museum of Art', title: 'Philadelphia Museum of Art'},
{id: 27, image: 'art24.jpg', alt: 'Philadelphia Museum of Art fountain', title: 'Philadelphia Museum of Art fountain'},
{id: 28, image: 'art25.jpg', alt: 'Jenn, Neal and Heidi', title: 'Jenn, Neal and Heidi'},
{id: 29, image: 'art26.jpg', alt: 'View from the Philadelphia Museum of Art', title: 'View from the Philadelphia Museum of Art'},
{id: 30, image: 'art27.jpg', alt: 'View from the Philadelphia Museum of Art', title: 'View from the Philadelphia Museum of Art'},
{id: 31, image: 'art28.jpg', alt: 'Another View', title: 'Another View'},
{id: 32, image: 'art29.jpg', alt: 'Adam', title: 'Adam resting at the top'},
{id: 33, image: 'art30.jpg', alt: 'Jenn sticking her tongue', title: 'Jenn sticking her tongue out'},
{id: 34, image: 'art31.jpg', alt: 'Statue on the Other Side', title: 'Statue on the Other Side'},
{id: 35, image: 'art32.jpg', alt: 'The Back Side', title: 'The Back Side'},
{id: 36, image: 'art33.jpg', alt: 'The Back Side Gardens', title: 'The Back Side Gardens'},
{id: 37, image: 'art34.jpg', alt: 'The Back Side Gardens', title: 'The Back Side Gardens'},
{id: 38, image: 'art35.jpg', alt: 'The Back Side Gardens', title: 'The Back Side Gardens'},
{id: 39, image: 'art36.jpg', alt: 'Statue', title: 'Statue'},


]

export const DANCEPICTURES: Picture[] = [
{id: 1, image: 'dance1.jpg', alt: 'Beyond the Art Musem', title: 'Beyond the Art Musem'},
{id: 2, image: 'dance2.jpg', alt: 'Philadelphia Skyline', title: 'Philadelphia Skyline'},
{id: 3, image: 'dance3.jpg', alt: 'Philadelphia Skyline', title: 'Philadelphia Skyline'},
{id: 4, image: 'dance4.jpg', alt: 'Fairmount Water Works', title: 'Fairmount Water Works'},
{id: 5, image: 'dance34.jpg', alt: 'Jenn at the Fairmount Water Works', title: 'Jenn at the Fairmount Water Works'},
{id: 6, image: 'dance35.jpg', alt: 'Jenn at the Fairmount Water Works', title: 'Jenn at the Fairmount Water Works'},
{id: 7, image: 'dance36.jpg', alt: 'Jenn and Heidi', title: 'Jenn and Heidi'},
{id: 8, image: 'dance5.jpg', alt: 'Schuylkill River', title: 'Schuylkill River'},
{id: 9, image: 'dance6.jpg', alt: 'Schuylkill River', title: 'Schuylkill River'},
{id: 10, image: 'dance7.jpg', alt: 'Schuylkill River', title: 'Schuylkill River'},
{id: 11, image: 'dance8.jpg', alt: 'Philadelphia Skyline', title: 'Philadelphia Skyline'},
{id: 12, image: 'dance9.jpg', alt: 'Fairmount Water Works', title: 'Fairmount Water Works'},
{id: 13, image: 'dance10.jpg', alt: 'Philadelphia Skyline', title: 'Philadelphia Skyline'},
{id: 14, image: 'dance12.jpg', alt: 'Schuylkill River', title: 'Schuylkill River'},
{id: 15, image: 'dance13.jpg', alt: 'Adam', title: 'Adam'},
{id: 16, image: 'dance14.jpg', alt: 'Jenn', title: 'Jenn'},
{id: 17, image: 'dance15.jpg', alt: 'Jenn', title: 'Jenn'},
{id: 18, image: 'dance16.jpg', alt: 'Schuylkill River', title: 'Schuylkill River'},
{id: 19, image: 'dance17.jpg', alt: 'Schuylkill River', title: 'Schuylkill River'},
{id: 20, image: 'dance18.jpg', alt: 'Schuylkill River', title: 'Schuylkill River'},
{id: 21, image: 'dance19.jpg', alt: 'Schuylkill River', title: 'Schuylkill River'},
{id: 22, image: 'dance20.jpg', alt: 'Fairmount Water Works', title: 'Fairmount Water Works'},
{id: 23, image: 'dance21.jpg', alt: 'Schuylkill River', title: 'Schuylkill River'},
{id: 24, image: 'dance22.jpg', alt: 'Schuylkill River', title: 'Schuylkill River'},
{id: 25, image: 'dance23.jpg', alt: 'Philadelphia Museum of Art', title: 'Philadelphia Museum of Art'},
{id: 26, image: 'dance24.jpg', alt: 'Piggyback ride', title: 'Piggyback ride'},
{id: 27, image: 'dance25.jpg', alt: 'Jenn and Neal', title: 'Jenn\'s feet hurt'},
{id: 28, image: 'dance26.jpg', alt: 'Lloyd Hall', title: 'Lloyd Hall'},
{id: 29, image: 'dance27.jpg', alt: 'Jewish Apple Cake', title: 'Jewish Apple Cake'},
{id: 30, image: 'dance28.jpg', alt: 'Neal dancing', title: 'Neal dancing'},
{id: 31, image: 'dance29.jpg', alt: 'Neal dancing', title: 'Neal dancing'},
{id: 32, image: 'dance30.jpg', alt: 'Neal needs water', title: 'Neal needs water'},
{id: 35, image: 'dance31.jpg', alt: 'Seven bottles of water for Neal', title: 'Seven bottles of water for Neal', description:'Neal was actually buying them for the dancers'},
{id: 34, image: 'dance32.jpg', alt: 'Jenn\'s excited', title: 'Jenn\'s excited'},
{id: 35, image: 'dance33.jpg', alt: 'Jenn\'s excited', title: 'Jenn\'s excited'},


]

export const PHILLYPICTURES: Picture[] = [
{id: 1, image: 'philadelphia28.jpg', alt: 'Towers', title: 'Towers'},
{id: 2, image: 'philadelphia29.jpg', alt: 'Answer Injustice with Justice', title: 'Answer Injustice with Justice', description: 'On a wall of things people wish: Impeach Donald Trump'},
{id: 3, image: 'philadelphia30.jpg', alt: 'Penn\'s Landing Statue', title: 'Penn\'s Landing Statue'},
{id: 4, image: 'philadlephia31.jpg', alt: 'Goodbye Philly', title: 'Goodbye Philly'},
{id: 5, image: 'philadlephia32.jpg', alt: 'Citizens Bank Park', title: 'Citizens Bank Park', description: 'Home of the Philadelphia Phillies'},
{id: 6, image: 'philadlephia33.jpg', alt: 'Citizen Bank Park', title: 'Citizens Bank Park and Philly'},
{id: 7, image: 'philadlephia34.jpg', alt: 'Lincoln Field', title: 'Lincoln Field', description: 'Home of the Philadelphia Eagles'},
{id: 8, image: 'philadlephia35.jpg', alt: 'Lincoln Field', title: 'Lincoln Field', description: 'Cue the theme song of It\'s Always Sunny in Philadelphia'},
{id: 9, image: 'philadlephia36.jpg', alt: 'Wells Fargo Center', title: 'Wells Fargo Center', description: 'Home of the Philadelphia 76ers and Philadelphia Flyers'},
{id: 10, image: 'philadlephia37.jpg', alt: 'Wells Fargo Center', title: 'Wells Fargo Center'},
{id: 11, image: 'philadlephia38.jpg', alt: 'Philadelphia', title: 'Philadelphia Freedom'},
{id: 12, image: 'philadlephia39.jpg', alt: 'Adam', title: 'Adam silly leaving Philadelphia'},
{id: 13, image: 'delaware10.jpg', alt: 'Wilmington', title: 'Wilmington on the way back from Philly'},
{id: 14, image: 'delaware11.jpg', alt: 'Delaware', title: 'More Delaware on the way back.'},
{id: 15, image: 'delaware12.jpg', alt: 'Delaware', title: 'Sun shining bright in Delaware'},
{id: 16, image: 'maryland4.jpg', alt: 'Sunset', title: 'Sunset from Susquehanna River'},
{id: 17, image: 'maryland5.jpg', alt: 'Baltimore', title: 'Baltimore from afar'},
{id: 18, image: 'maryland6.jpg', alt: 'Blobs Road', title: 'Blobs Road?'}
]

export const CHIDOPICTURES: Picture[] = [
  {id: 1, image: 'chido1.jpg', alt: 'Chido\'s', title: 'Chido\'s'},
  {id: 2, image: 'chido2.jpg', alt: 'Margarita', title: 'Margarita'},
  {id: 3, image: 'chido3.jpg', alt: 'Taco Salad', title: 'Taco Salad'}  
]

/*    {id: , image: '.jpg', alt: '', title: ''},*/
